spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gollajo-testdb.cgrh78ev6hez.ap-northeast-2.rds.amazonaws.com:3306/gollajo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dkwneo19!
    dbcp:
      testOnBorrow: true
      validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
cloud:
  aws:
    s3:
      bucket: gollajo
    credentials:
      access-key: AKIA6EN5HXX5TOMN4SB4
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
oauth:
  kakao:
    info:
      grant-type: authorization_code
      client-id: 947a77772be98f9fa28952bd29c79488
      client-secret: Ro1cjQrUC7x7nixeIuLLobUDy1v9nTS8
      redirect-info: http://localhost:8080/oauth/kakao/callback
jwt:
  token:
    secret-key: hamerisgoodhamersogoodhamergood
    expiration-time: 1800000
gollajo:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080